pipeline:
  name: "spec2code_pipeline"
  description: "Main pipeline for generating implementation plans from feature descriptions"
  
  # Sequential execution of agents
  agents:
    - name: "plan_maker"
      input_key: "pipeline_input"  # Takes the initial pipeline input
      output_key: "implementation_plan"  # Output will be stored with this key
      prompt_templates: "with_context"  # Use with_context template from prompts.yaml
      
    - name: "plan_critique_generator"
      input_key: "implementation_plan"  # Takes output from previous agent
      output_key: "critique_report"  # Output will be stored with this key
      prompt_templates: "technical_feasibility"  # Use technical_feasibility template from prompts.yaml
      
    - name: "plan_critique_comparator"
      input_key: "critique_report"  # Takes output from previous agent
      output_key: "comparison_result"  # Final output
      prompt_templates: "detailed_comparison"  # Use detailed_comparison template from prompts.yaml
  
  # Execution settings
  execution:
    mode: "sequential"  # Future: could be "parallel"
    
  # Pipeline-level settings
  settings:
    log_level: "INFO"
