pipeline:
  name: "requirements_generator_pipeline"
  description: "Pipeline for generating formal requirements JSON documents from brief descriptions"
  
  agents:
    - name: "business_analyst"
      inputs: ["pipeline_input"]
  
  execution:
    mode: "sequential"
    
  settings:
    log_level: "DEBUG"
    create_run_artifacts: true
    include_messages_in_artifacts: true
    runs_directory: "runs"
