name: "plan_maker"
description: "Creates detailed implementation plans from decomposed steps"
llm: "openai_gpt4"
tools:
  - name: "file_reader"
    description: "Read context files for planning"
    _type: "file_reader"
    base_path: "./context"
  - name: "project_analyzer"
    description: "Analyze project structure and dependencies"
    _type: "file_reader"
    base_path: "./projects"
memory:
  _type: "buffer"
  max_token_limit: 2000
agent_type: "zero-shot-react-description"
max_iterations: 3
early_stopping_method: "generate"
